# This file is machine-generated - editing it directly is not advised

[[UnsafeArrays]]
git-tree-sha1 = "417100df8567333bff1b851008b1441a2be08da0"
uuid = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
version = "0.4.0"
